const biotechnology = [
    { key: 1, name: "CELL BIOLOGY AND GENETICS" },
    { key: 2, name: "INTRODUCTORY MATHEMATICS-I (FOR NEET STUDENTS)" },
    { key: 3, name: "MATHEMATICS-I FOR JEE STUDENTS" },
    { key: 4, name: "BIOCHEMISTRY-I" },
    { key: 5, name: "INTRODUCTORY MATHEMATICS-II (FOR NEET STUDENTS)" },
    { key: 6, name: "MATHEMATICS-II (FOR JEE STUDENTS)" },
    { key: 7, name: "BIOCHEMISTRY AND MICROBIOLOGY LAB" },
    { key: 8, name: "FOOD SCIENCE AND NUTRITION" },
    { key: 9, name: "IMMUNOTECHNOLOGY" },
    { key: 10, name: "BIOCHEMISTRY-II" },
    { key: 11, name: "MOLECULAR BIOLOGY" },
    { key: 12, name: "BIOPHYSICS AND BIOMATERIALS" },
    { key: 13, name: "MOLECULAR BIOLOGY, FOOD SCIENCE AND IMMUNOLOGY LAB" },
    { key: 14, name: "BIOANALYTICAL TECHNIQUES" },
    { key: 15, name: "GENETIC & METABOLIC ENGINEERING" },
    { key: 16, name: "ANIMAL BIOTECHNOLOGY" },
    { key: 17, name: "PLANT BIOTECHNOLOGY" },
    { key: 18, name: "ANIMAL AND PLANT BIOTECHNOLOGY LAB" },
    { key: 19, name: "BIOSTATISTICS" },
    { key: 20, name: "BIOINFORMATICS" },
    { key: 21, name: "BIOPROCESS ENGINEERING" },
    { key: 22, name: "TRANSDUCERS AND BIOSENSORS" },
    { key: 23, name: "BIOSTATISTICS AND OMICS LAB" },
    { key: 24, name: "DOWNSTREAM PROCESSING" },
    { key: 25, name: "PHARMACEUTICAL TECHNOLOGY" },
    { key: 26, name: "BIOSAFETY, BIOETHICS & IPR" },
    { key: 27, name: "JOURNAL CLUB" },
    { key: 28, name: "PROCESS LAB" },
    { key: 29, name: "GENOMICS AND PROTEOMICS" },
    { key: 30, name: "ENZYME TECHNOLOGY" },
    { key: 31, name: "NANOBIOTECHNOLOGY" },
    { key: 32, name: "CONCEPTS IN BIOMEDICAL INSTRUMENTATION" },
    { key: 33, name: "INDUSTRIAL BIOTECHNOLOGY" },
]

export default biotechnology;