const common = [
    { key: 1, name: "OBJECT ORIENTED PROGRAMMING" },
    { key: 2, name: "DISCRETE MATHEMATICS" },
    { key: 3, name: "OPERATING SYSTEMS" },
    { key: 4, name: "DATABASE MANAGEMENT SYSTEMS" },
    { key: 5, name: "DESIGN AND ANALYSIS OF ALGORITHMS" },
    { key: 6, name: "COMPUTER NETWORKS" },
    { key: 7, name: "ARTIFICIAL INTELLIGENCE" },
    { key: 8, name: "DATA STRUCTURES" },
    { key: 9, name: "DISCRETE MATHEMATICAL STRUCTURES" },
    { key: 10, name: "ENGINEERING MATERIALS" },
    { key: 11, name: "MACHINE LEARNING" },
    { key: 12, name: "THEORY OF COMPUTATION" },
    { key: 13, name: "SOCIAL NETWORK ANALYSIS" },
    { key: 14, name: "ETHICAL HACKING" },
    { key: 15, name: "COMPUTER ARCHITECTURE AND ORGANIZATION" },
    { key: 16, name: "OPTIMIZATION TECHNIQUES" },
    { key: 17, name: "SOLIDS AND STRUCTURES" },
    { key: 18, name: "MANUFACTURING PROCESSES" },
    { key: 19, name: "ENGINEERING DESIGN PROJECT" },
    { key: 20, name: "NUMERICAL ANALYSIS" },
    { key: 21, name: "MATERIAL AND ENERGY BALANCES" },
    { key: 22, name: "HEAT TRANSFER" },
    { key: 23, name: "DATA STRUCTURES AND ALGORITHMS" },
    { key: 24, name: "ANALOG AND DIGITAL COMMUNICATION" },
    { key: 25, name: "PROFESSIONAL COMMUNICATION" },
    { key: 26, name: "ENERGY AND ENVIRONMENT" },
    { key: 27, name: "PHYSICS" },
    { key: 28, name: "ENGINEERING DRAWING" },
    { key: 29, name: "MATHEMATICS-I" },
    { key: 30, name: "CHEMISTRY" },
    { key: 31, name: "PROGRAMMING FOR PROBLEM SOLVING" },
    { key: 32, name: "ELECTRICAL & ELECTRONICS ENGINEERING" },
    { key: 33, name: "MATHEMATICS-II" },
    { key: 34, name: "ENGINEERING DESIGN PROJECT - I" },
    { key: 35, name: "ENGINEERING DESIGN PROJECT - II" },
    { key: 36, name: "HUMANITIES FOR ENGINEERS" },
    { key: 37, name: "EMPLOYABILITY DEVELOPMENT SKILLS" },
    { key: 38, name: "EVOLUTIONARY PSYCHOLOGY" },
    { key: 39, name: "ENGINEERING DESIGN PROJECT (BUGGY)" },
    { key: 40, name: "INNOVATION AND ENTREPRENEURSHIP" },
    { kye: 41, name: "OTHER"}
]

export default common;