const computer = [
    { key: 1, name: "PROBABILITY AND STATISTICS" },
    { key: 2, name: "FUNDAMENTALS OF COMPUTER SCIENCE" },
    { key: 3, name: "PRINCIPLES OF ELECTRICAL ENGINEERING" },
    { key: 4, name: "FUNDAMENTALS OF PHYSICS" },
    { key: 5, name: "BUSINESS COMMUNICATION & VALUE SCIENCE - 1" },
    { key: 6, name: "LINEAR ALGEBRA" },
    { key: 7, name: "STATISTICAL MODELING" },
    { key: 8, name: "DATA STRUCTURES & ALGORITHMS" },
    { key: 9, name: "PRINCIPLES OF ELECTRONICS" },
    { key: 10, name: "FUNDAMENTALS OF ECONOMICS" },
    { key: 11, name: "BUSINESS COMMUNICATION & VALUE SCIENCE -11" },
    { key: 12, name: "ENVIRONMENTAL SCIENCES" },
    { key: 13, name: "FORMAL LANGUAGE AND AUTOMATA THEORY" },
    { key: 14, name: "COMPUTER ORGANIZATION & ARCHITECTURE" },
    { key: 15, name: "COMPUTATIONAL STATISTICS" },
    { key: 16, name: "SOFTWARE ENGINEERING" },
    { key: 17, name: "INDIAN CONSTITUTION (NON-CREDIT)" },
    { key: 18, name: "SOFTWARE DESIGN WITH UML" },
    { key: 19, name: "INTRODUCTION TO INNOVATION, IP MANAGEMENT AND ENTREPRENEURSHIP" },
    { key: 20, name: "DESIGN THINKING" },
    { key: 21, name: "OPERATIONS RESEARCH" },
    { key: 22, name: "MARKETING RESEARCH & MARKETING MANAGEMENT" },
    { key: 23, name: "ESSENCE OF INDIAN TRADITIONAL KNOWLEDGE (NON-CREDIT)" },
    { key: 24, name: "COMPILER DESIGN" },
    { key: 25, name: "FUNDAMENTALS OF MANAGEMENT" },
    { key: 26, name: "BUSINESS STRATEGY" },
    { key: 27, name: "BUSINESS COMMUNICATION & VALUE SCIENCE-III" },
    { key: 28, name: "INFORMATION SECURITY" },
    { key: 29, name: "FINANCIAL & COST ACCOUNTING" },
    { key: 30, name: "BUSINESS COMMUNICATION & VALUE SCIENCE-IV" },
    { key: 31, name: "USABILITY DESIGN OF SOFTWARE APPLICATIONS" },
    { key: 32, name: "IT WORKSHOP SKYLAB/MATLAB" },
    { key: 33, name: "FINANCIAL MANAGEMENT" },
    { key: 34, name: "HUMAN RESOURCE MANAGEMENT" },
    { key: 35, name: "SERVICES SCIENCE & SERVICE OPERATIONAL MANAGEMENT" },
    { key: 36, name: "IT PROJECT MANAGEMENT" },
    { key: 37, name: "OPERATING SYSTEM" },
    { key: 38, name: "NUMERICAL LINEAR ALGEBRA" },
    { key: 39, name: "CLOUD COMPUTING" },
    { key: 40, name: "NETWORK PROGRAMMING" },
    { key: 41, name: "COMPUTER GRAPHICS" },
    { key: 42, name: "QUANTUM COMPUTING" },
    { key: 43, name: "COMPILER CONSTRUCTION" },
    { key: 44, name: "COGNITIVE COMPUTING" },
    { key: 45, name: "MICROPROCESSOR-BASED SYSTEMS DESIGN" },
    { key: 46, name: "EMBEDDED SYSTEMS DESIGN" },
]

export default computer;